version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same Wi-Fi, for instance.

services:
  seq:
    environment:
      - ACCEPT_EULA=Y

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    volumes:
      - eshop-sqldata:/var/opt/mssql

  nosqldata:
    volumes:
      - eshop-nosqldata:/data/db

  basketdata:
    volumes:
      - eshop-basketdata:/data

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webspa_port}
      - XamarinCallback=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}/xamarincallback
      - ConnectionStrings__IdentityDb=Server=sqldata_${tjobname},1433;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
      - MvcClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webmvc_port}
      - BasketApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${basket_api_port}
      - OrderingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${ordering_api_port}
      - MobileShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${mobileshoppingagg_port}
      - WebShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webshoppingagg_port}
      - WebhooksApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webhooks_api_port}
      - WebhooksWebClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webhooksclient_port}
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "${identity_api_port}:80"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - ConnectionStrings__Redis=basketdata_${tjobname}
      - ConnectionStrings__EventBus=rabbitmq_${tjobname}
      - Identity__Url=http://identity_api_${tjobname}
      - Identity__ExternalUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}
      - EventBus__UserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBus__Password=${ESHOP_SERVICE_BUS_PASSWORD}
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - PATH_BASE=/basket_api_${tjobname}
    ports:
      - "${basket_api_port}:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - ConnectionStrings__CatalogDb=Server=sqldata_${tjobname},1433;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
      - ConnectionStrings__EventBus=rabbitmq_${tjobname}
      - PicBaseUrl=${ESHOP_STORAGE_CATALOG_URL}
      - EventBus__UserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBus__Password=${ESHOP_SERVICE_BUS_PASSWORD}
      - AzureStorageAccountName=${ESHOP_AZURE_STORAGE_CATALOG_NAME}
      - AzureStorageAccountKey=${ESHOP_AZURE_STORAGE_CATALOG_KEY}
      - UseCustomizationData=True
      - AzureStorageEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - PATH_BASE=/catalog_api_${tjobname}

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - ConnectionStrings__OrderingDb=Server=sqldata_${tjobname},1433;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
      - ConnectionStrings__EventBus=rabbitmq_${tjobname}
      - Identity__Url=http://identity_api_${tjobname}
      - Identity__ExternalUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}
      - EventBus__UserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBus__Password=${ESHOP_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - PATH_BASE=/ordering_api_${tjobname}
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "${ordering_api_port}:80"
      - "${ordering_api_hc_port}:81"

  ordering-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__OrderingDb=Server=sqldata_${tjobname},1433;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
      - ConnectionStrings__EventBus=rabbitmq_${tjobname}
      - EventBus__UserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBus__Password=${ESHOP_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - GracePeriodTime=1
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__EventBus=rabbitmq_${tjobname}
      - EventBus__UserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBus__Password=${ESHOP_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}

  webhooks-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__WebhooksDb=Server=sqldata_${tjobname},1433;Database=Microsoft.eShopOnContainers.Services.WebhooksDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
      - ConnectionStrings__EventBus=rabbitmq_${tjobname}
      - EventBus__UserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBus__Password=${ESHOP_SERVICE_BUS_PASSWORD}
      - Identity__Url=http://identity_api_${tjobname}
      - Identity__ExternalUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}
    ports:
      - "${webhooks_api_port}:80"

  mobileshoppingapigw:
    volumes:
      - ./tmp/${tjobname}/mobileshopping:/etc/envoy

  webshoppingapigw:
    volumes:
      - ./tmp/${tjobname}/webshopping:/etc/envoy

  mobileshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket_api_${tjobname}
      - urls__catalog=http://catalog_api_${tjobname}
      - urls__orders=http://ordering_api_${tjobname}
      - urls__identity=http://identity_api_${tjobname}
      - urls__grpcBasket=http://basket_api_${tjobname}:81
      - urls__grpcCatalog=http://catalog_api_${tjobname}:81
      - urls__grpcOrdering=http://ordering_api_${tjobname}:81
      - CatalogUrlHC=http://catalog_api_${tjobname}/hc
      - OrderingUrlHC=http://ordering_api_${tjobname}/hc
      - IdentityUrlHC=http://identity_api_${tjobname}/hc
      - BasketUrlHC=http://basket_api_${tjobname}/hc
      - PaymentUrlHC=http://payment_api_${tjobname}/hc
      - Identity__Url=http://identity_api_${tjobname}
      - Identity__ExternalUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}
    ports:
      - "${mobileshoppingagg_port}:80"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket_api_${tjobname}
      - urls__catalog=http://catalog_api_${tjobname}
      - urls__orders=http://ordering_api_${tjobname}
      - urls__identity=http://identity_api_${tjobname}
      - urls__grpcBasket=http://basket_api_${tjobname}:81
      - urls__grpcCatalog=http://catalog_api_${tjobname}:81
      - urls__grpcOrdering=http://ordering_api_${tjobname}:81
      - ReverseProxy__Clusters__basket__Destinations__destination0__Address=http://basket_api_${tjobname}
      - ReverseProxy__Clusters__catalog__Destinations__destination0__Address=http://catalog_api_${tjobname}
      - ReverseProxy__Clusters__orders__Destinations__destination0__Address=http://ordering_api_${tjobname}
      - ReverseProxy__Clusters__signalr__Destinations__destination0__Address=http://ordering_signalrhub_${tjobname}
      - CatalogUrlHC=http://catalog_api_${tjobname}/hc
      - OrderingUrlHC=http://ordering_api_${tjobname}/hc
      - IdentityUrlHC=http://identity_api_${tjobname}/hc
      - BasketUrlHC=http://basket_api_${tjobname}/hc
      - PaymentUrlHC=http://payment_api_${tjobname}/hc
      - Identity__Url=http://identity_api_${tjobname}
      - Identity__ExternalUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}
    ports:
      - "${webshoppingagg_port}:80"

  ordering-signalrhub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__EventBus=rabbitmq_${tjobname}
      - EventBus__UserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBus__Password=${ESHOP_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - Identity__Url=http://identity_api_${tjobname}
    ports:
      - "${orderingsignalhub_port}:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=WebMVC HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://webmvc_${tjobname}/hc
      - HealthChecksUI__HealthChecks__1__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://webspa_${tjobname}/hc
      - HealthChecksUI__HealthChecks__2__Name=Web Shopping Aggregator GW HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://webshoppingagg_${tjobname}/hc
      - HealthChecksUI__HealthChecks__3__Name=Mobile Shopping Aggregator HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://mobileshoppingagg_${tjobname}/hc
      - HealthChecksUI__HealthChecks__4__Name=Ordering HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://ordering_api_${tjobname}/hc
      - HealthChecksUI__HealthChecks__5__Name=Basket HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=http://basket_api_${tjobname}/hc
      - HealthChecksUI__HealthChecks__6__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__6__Uri=http://catalog_api_${tjobname}/hc
      - HealthChecksUI__HealthChecks__7__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__7__Uri=http://identity_api_${tjobname}/hc
      - HealthChecksUI__HealthChecks__8__Name=Payments HTTP Check
      - HealthChecksUI__HealthChecks__8__Uri=http://payment_api_${tjobname}/hc
      - HealthChecksUI__HealthChecks__9__Name=Ordering SignalRHub HTTP Check
      - HealthChecksUI__HealthChecks__9__Uri=http://ordering_signalrhub_${tjobname}/hc
      - HealthChecksUI__HealthChecks__10__Name=Ordering HTTP Background Check
      - HealthChecksUI__HealthChecks__10__Uri=http://ordering_backgroundtasks_${tjobname}/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}
      - PurchaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webshoppingagg_port}
      - IdentityUrlHC=http://identity_api_${tjobname}/hc
      - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webshoppingagg_port}
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "${webspa_port}:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PurchaseUrl=http://webshoppingagg_${tjobname}
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}
      - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webshoppingagg_port}
      - IdentityUrlHC=http://identity_api_${tjobname}/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "${webmvc_port}:80"

  webhooks-client:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Token=6168DB8D-DC58-4094-AF24-483278923590      # Webhooks are registered with this token (any value is valid) but the client won't check it
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${identity_api_port}
      - CallBackUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:${webhooksclient_port}
      - WebhooksUrl=http://webhooks_api_${tjobname}
      - SelfUrl=http://webhooks_client_${tjobname}/
    ports:
      - "${webhooksclient_port}:80"
volumes:
  eshop-sqldata:
    name: eshop-sqldata_${tjobname}
    external: false
  eshop-nosqldata:
    name: eshop-nosqldata_${tjobname}
    external: false
  eshop-basketdata:
    name: eshop-basketdata_${tjobname}
    external: false