version: '3.4'

services:

  seq-${tjobname}:
    container_name: seq-${tjobname}
    image: datalust/seq:latest
    networks:
      - jenkins_network

  sqldata-${tjobname}:
    container_name: sqldata-${tjobname}
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - jenkins_network

  nosqldata-${tjobname}:
    container_name: nosqldata-${tjobname}
    image: mongo
    networks:
      - jenkins_network

  basketdata-${tjobname}:
    container_name: basketdata-${tjobname}
    image: redis:alpine
    networks:
      - jenkins_network

  rabbitmq-${tjobname}:
    container_name: rabbitmq-${tjobname}
    image: rabbitmq:3-management-alpine
    networks:
      - jenkins_network

  identity-api-${tjobname}:
    container_name: identity-api-${tjobname}
    image: ${REGISTRY:-eshop}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sqldata-${tjobname}
    networks:
      - jenkins_network

  basket-api-${tjobname}:
    container_name: basket-api-${tjobname}
    image: ${REGISTRY:-eshop}/basket.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata-${tjobname}
      - identity-api-${tjobname}
      - rabbitmq-${tjobname}
    networks:
      - jenkins_network

  catalog-api-${tjobname}:
    container_name: catalog-api-${tjobname}
    image: ${REGISTRY:-eshop}/catalog.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sqldata-${tjobname}
      - rabbitmq-${tjobname}
    networks:
      - jenkins_network

  ordering-api-${tjobname}:
    container_name: ordering-api-${tjobname}
    image: ${REGISTRY:-eshop}/ordering.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - sqldata-${tjobname}
      - rabbitmq-${tjobname}
    networks:
      - jenkins_network

  ordering-backgroundtasks-${tjobname}:
    container_name: ordering-backgroundtasks-${tjobname}
    image: ${REGISTRY:-eshop}/ordering.backgroundtasks:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - sqldata-${tjobname}
      - rabbitmq-${tjobname}
    networks:
      - jenkins_network

  payment-api-${tjobname}:
    container_name: payment-api-${tjobname}
    image: ${REGISTRY:-eshop}/payment.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq-${tjobname}
    networks:
      - jenkins_network

  webhooks-api-${tjobname}:
    container_name: webhooks-api-${tjobname}
    image: ${REGISTRY:-eshop}/webhooks.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile
    depends_on:
      - sqldata-${tjobname}
    networks:
      - jenkins_network

  mobileshoppingapigw-${tjobname}:
    container_name: mobileshoppingapigw-${tjobname}
    image: envoyproxy/envoy:v1.11.1
    networks:
      - jenkins_network

  mobileshoppingagg-${tjobname}:
    container_name: mobileshoppingagg-${tjobname}
    image: ${REGISTRY:-eshop}/mobileshoppingagg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata-${tjobname}
      - sqldata-${tjobname}
      - identity-api-${tjobname}
      - rabbitmq-${tjobname}
      - ordering-api-${tjobname}
      - catalog-api-${tjobname}
      - basket-api-${tjobname}
    networks:
      - jenkins_network

  webshoppingagg-${tjobname}:
    container_name: webshoppingagg-${tjobname}
    image: ${REGISTRY:-eshop}/webshoppingagg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata-${tjobname}
      - sqldata-${tjobname}
      - identity-api-${tjobname}
      - rabbitmq-${tjobname}
      - ordering-api-${tjobname}
      - catalog-api-${tjobname}
      - basket-api-${tjobname}
    networks:
      - jenkins_network

  ordering-signalrhub-${tjobname}:
    container_name: ordering-signalrhub
    image: ${REGISTRY:-eshop}/ordering.signalrhub:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata-${tjobname}
      - sqldata-${tjobname}
      - identity-api-${tjobname}
      - rabbitmq-${tjobname}
      - ordering-api-${tjobname}
      - catalog-api-${tjobname}
      - basket-api-${tjobname}
    networks:
      - jenkins_network

  webstatus-${tjobname}:
    container_name: webstatus-${tjobname}
    image: ${REGISTRY:-eshop}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile
    networks:
      - jenkins_network

  webspa-${tjobname}:
    container_name: webspa-${tjobname}
    image: ${REGISTRY:-eshop}/webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:16-bullseye}
    depends_on:
      - webshoppingagg-${tjobname}
    networks:
      - jenkins_network

  webmvc-${tjobname}:
    container_name: webmvc-${tjobname}
    image: ${REGISTRY:-eshop}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg-${tjobname}
    networks:
      - jenkins_network

  webhooks-client-${tjobname}:
    container_name: webhooks-client-${tjobname}
    image: ${REGISTRY:-eshop}/webhooks.client:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api-${tjobname}
    networks:
      - jenkins_network

  webshoppingapigw-${tjobname}:
    container_name: webshoppingapigw
    image: envoyproxy/envoy:v1.11.1
    networks:
      - jenkins_network

networks:
  jenkins_network:
    external: true