name: build
on:
  push:
#    branches-ignore:
#      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
#      - 'gh-pages' #github pages do not trigger all tests
#    tags-ignore:
#      - 'v*' #avoid rerun existing commit on release
#  pull_request:
#    branches:
#      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    #if: ${{ false }}  # disable for now
    permissions: 
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build only, tests run in on-premises Jenkins
        run: mvn test -U --no-transfer-progress
